language: python

install:
  - sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic texlive-generic-extra
  - git checkout $TRAVIS_BRANCH


script:
  - python3 script.py

addons:
  apt:
    packages: texlive-latex-base 
              texlive-fonts-recommended 
              texlive-fonts-extra 
              texlive-latex-extra 
              texlive-lang-cyrillic
              texlive-generic-extra


after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add -A
  - git commit --message "Travis build - $TRAVIS_BUILD_NUMBER"
  - git push
  